### ISSUE TITLE
Internal WMUPDV Interpolation to curvilinear grids is slow

### ISSUE THREAD

**Issue by ajhenrique** [NOAA-EMC/WW3#180]
Model runs are suffering a few seconds slow down when interpolating inputs from an arbitrary grid  internally to a cruvilinear grid. Solutions to the issue being considered:

1 - Add OMP loops to improve performance in OMP or MPI+OMP builds
2 - Saving weights in WMUPDV 
3 - Create import grids for each computational WW3 grid and have the connectors directly send information there or use EMSF RH in the cap instead of calling wmupd2

(with @JessicaMeixner-NOAA)

**Comment by ajhenrique** [comment]
Solution (1) was implemented. Provided speed up roughly proportional to the number of OMP processes. Solved by @JamesAbeles-NOAA

**Comment by ajhenrique** [comment]
This issue will remain open for consideration of options (2) and (3).

**Comment by JessicaMeixner-NOAA** [comment]
This issue has been partially resolved.  Some updates towards speeding the interpolation were implemented in the code, but the issue remained open to explore additional ways to speed this part of the code up.  At this time there is no planned effort to revist this speed-up so the issue is going to be closed.  If someone would like to take on these speed-up efforts, please re-open or create a new issue.
