### ISSUE TITLE
Wave model cannot restart if mediator flag is set to startup

### ISSUE THREAD

**Issue by pjpegion** [NOAA-EMC/WW3#870]
**Describe the bug**
The wave model cannot start if wave information is not in the coupler.  The solution should be to set
start_type = startup in the nems.configure file, but when doing this, WW3 gets the wrong model time.

**To Reproduce**
set KEEP to true in rt.sh
Run the cpld_control_p8 and cpld_restart_p8 tests.
In the cpld_restart_p8 directory change
start_type = continue to
start_type = initial
and model will have an error with a time mismatch.

**Expected behavior**

The wave model should be initialing with the current time, not the forecast start time.

**Comment by mickaelaccensi** [comment]
@DeniseWorthen, do you think your PR #877 solved this issue ?

**Comment by DeniseWorthen** [comment]
@mickaelaccensi My #877 was closed w/o merging in favor of a PR https://github.com/NOAA-EMC/WW3/pull/871. The relevant line that was added in that PR was 

https://github.com/NOAA-EMC/WW3/blob/d9b3172f4197c65d471662c6952a668152d71230/model/src/wav_comp_nuopc.F90#L618-L620

Are you running using the CESMCOUPLED flag?

**Comment by mickaelaccensi** [comment]
no I don't have this issue, we are just trying to check if some solved issues could be closed, so I let you close this one if you consider it as solved by PR #871

**Comment by JessicaMeixner-NOAA** [comment]
The PR states in #871 that it fixes this issue, so I'm going to close this issue.  Others can reopen if they feel it is not solved.   Thanks for checking in on this @mickaelaccensi
